version: "3.7"
services:
  bentoml_service:
    image: longlam071/model_serving:latest
    container_name: online_serving
    restart: on-failure
    environment:
      - DAGS_DIR="../mlops-crash-course-platform/airflow/run_env/dags/model_serving"
      - FEAST_ONLINE_STORE_HOST="host.docker.internal"
    volumes:
      - ../artifacts:/model_serving/artifacts
      - ../feature_repo:/model_serving/feature_repo
    command: /bin/bash scripts/bentoml_helper.sh serve --port=6789
    ports:
      - 6789:6789